# Generated by Django 3.0.2 on 2020-06-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='projects',
        ),
    ]
