# Generated by Django 3.0.2 on 2020-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200621_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/defaultdp.jpg', null=True, upload_to=''),
        ),
    ]
