# Generated by Django 3.0.2 on 2020-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200622_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/logos/defaultdp.jpg', null=True, upload_to='logos'),
        ),
    ]
