# Generated by Django 3.0.2 on 2020-06-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200622_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default='media\\logos\\defaultdp.jpg', null=True, upload_to='logos'),
        ),
    ]
