# Generated by Django 3.0.2 on 2020-06-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200622_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='Narowal', max_length=100, null=True),
        ),
    ]
