# Generated by Django 3.0.2 on 2020-06-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200622_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(default=None, upload_to='CompanyMOUs'),
            preserve_default=False,
        ),
    ]
