# Generated by Django 3.0.2 on 2020-06-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200619_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='develop_by',
            new_name='developed_by',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='develop_for',
            new_name='developed_for',
        ),
    ]
