# Generated by Django 3.0.2 on 2020-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200619_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bidding_start',
            field=models.DateTimeField(),
        ),
    ]
