# Generated by Django 3.0.2 on 2020-06-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_projects'),
        ('university', '0003_remove_university_projects'),
        ('project', '0005_project_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developed_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
