# Generated by Django 3.0.2 on 2020-06-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_collaboration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='company_mou',
            field=models.FileField(upload_to='CompnyMOUs'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='university_mou',
            field=models.FileField(blank=True, null=True, upload_to='UniversityMOUs'),
        ),
    ]
