# Generated by Django 3.0.2 on 2020-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200622_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='company_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='university_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
