# Generated by Django 3.0.2 on 2020-06-24 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
