# Generated by Django 3.0.2 on 2020-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_milestones_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='company_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='university_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='company_mou',
            field=models.FileField(blank=True, null=True, upload_to='CompnyMOUs'),
        ),
    ]
