# Generated by Django 3.0.2 on 2020-06-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200629_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='company_deal',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='university_deal',
        ),
        migrations.AddField(
            model_name='project',
            name='company_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='university_deal',
            field=models.BooleanField(default=False),
        ),
    ]
