# Generated by Django 3.0.2 on 2020-06-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20200629_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_mou',
            field=models.FileField(blank=True, null=True, upload_to='CompnyMOUs'),
        ),
        migrations.AddField(
            model_name='project',
            name='company_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='university_mou',
            field=models.FileField(blank=True, null=True, upload_to='UniversityMOUs'),
        ),
        migrations.AddField(
            model_name='project',
            name='university_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
    ]
