# Generated by Django 3.0.2 on 2020-07-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20200629_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
