# Generated by Django 3.0.2 on 2020-06-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20200619_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='projects',
        ),
    ]
