# Generated by Django 3.0.2 on 2020-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_university_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='ranking',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
