# Generated by Django 3.0.2 on 2020-06-22 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_university_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='UniversityMOUs'),
            preserve_default=False,
        ),
    ]
