# Generated by Django 3.0.2 on 2020-07-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='revisions',
            field=models.IntegerField(default=1),
        ),
    ]
